package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/coretech/dtc-api-gateway/internal/app/gateway/domain"
)

// GetTransactions is the resolver for the GetTransactions field.
func (r *queryResolver) GetTransactions(ctx context.Context, filter *domain.TransactionFilter, limit *int, skip *int) ([]domain.Transaction, error) {
	f := domain.TransactionFilter{}
	l := 10
	s := 0
	if filter != nil {
		f = *filter
	}

	if limit != nil {
		l = *limit
	}

	if skip != nil {
		s = *skip
	}

	return r.transaction.Get(ctx, f, l, s)
}
